// <auto-generated />
namespace Techlabs.Euphoria.Kernel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v53 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v53));
        
        string IMigrationMetadata.Id
        {
            get { return "201703311407513_v53"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
