SELECT * FROM Students

SET IDENTITY_INSERT dbo.Students ON
INSERT INTO Students(ID,NAME,AGE,CITY,CGPA) VALUES (101,'AKASH',21,'AHMEDABAD',6.97);

SET IDENTITY_INSERT dbo.Students ON
INSERT INTO Students(ID,NAME,AGE,CITY,CGPA) VALUES (102,'GAURANG',20,'AHMEDABAD',7.50);
INSERT INTO Students(ID,NAME,AGE,CITY,CGPA) VALUES (103,'BRIJESH',22,'MUMBAI',8.50);
INSERT INTO Students(ID,NAME,AGE,CITY,CGPA) VALUES (104,'HIMANSHU',21,'mUMBAI',6.50);
INSERT INTO Students(ID,NAME,AGE,CITY,CGPA) VALUES (105,'JAY',22,'AHMEDABAD',7.40);