// <auto-generated />
namespace ShoppingCartCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddToDatabse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddToDatabse));
        
        string IMigrationMetadata.Id
        {
            get { return "201803080927116_Add To Databse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
