SELECT * FROM Departments;
SELECT * FROM Employees;

SET IDENTITY_INSERT Departments ON 
GO

INSERT INTO Departments VALUES (10,'ACCOUNTING','NEW YORK');
INSERT INTO Departments VALUES (20,'RESEARCH','DALLAS');
INSERT INTO Departments VALUES (30,'SALES','CHICAGO');
INSERT INTO Departments VALUES (40,'OPERATIONS','BOSTON');
